import { CompanyListing, SectorClassification } from "@/types/index-directory";

export const mockSectorClassifications: SectorClassification[] = [
  { id: "1", name: "Agriculture & Agribusiness", slug: "agriculture", description: "Farming, processing, export", icon: "🌾", listingCount: 342 },
  { id: "2", name: "Manufacturing", slug: "manufacturing", description: "Production and assembly", icon: "🏭", listingCount: 289 },
  { id: "3", name: "Technology & ICT", slug: "technology", description: "Software, hardware, services", icon: "💻", listingCount: 198 },
  { id: "4", name: "Fashion & Textiles", slug: "fashion", description: "Apparel, fabrics, accessories", icon: "👗", listingCount: 156 },
  { id: "5", name: "Energy & Renewables", slug: "energy", description: "Solar, power solutions", icon: "⚡", listingCount: 134 },
  { id: "6", name: "Healthcare & Pharmaceuticals", slug: "healthcare", description: "Medical supplies, pharma", icon: "🏥", listingCount: 98 },
  { id: "7", name: "Construction & Real Estate", slug: "construction", description: "Building materials, development", icon: "🏗️", listingCount: 167 },
  { id: "8", name: "Logistics & Transport", slug: "logistics", description: "Freight, warehousing, delivery", icon: "🚚", listingCount: 112 },
];

export const mockCompanyListings: CompanyListing[] = [
  {
    id: "idx1",
    userId: "u1",
    companyName: "Okafor Agro Exports Limited",
    slug: "okafor-agro-exports",
    logo: "https://images.unsplash.com/photo-1599909533879-6bc6d6ce4932?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&h=400&fit=crop",
    tagline: "Premium African Agricultural Products for Global Markets",
    description: "Leading exporter of organic cashews, dried mangoes, and agricultural products from West Africa. Certified organic and fair trade. Serving international buyers since 2015.",
    sector: "Agriculture & Agribusiness",
    industries: ["Organic Agriculture", "Food Processing", "Export Trading"],
    country: "Nigeria",
    city: "Lagos",
    website: "www.okaforagroexports.com",
    email: "info@okaforagroexports.com",
    phone: "+234 123 456 7890",
    foundedYear: 2015,
    employeeCount: "50-100",
    annualRevenue: "$1M - $5M",
    exportMarkets: ["United States", "United Kingdom", "Germany", "Netherlands", "France"],
    certifications: ["Organic Certification", "HACCP", "Fair Trade", "ISO 9001"],
    products: ["Organic Cashew Nuts", "Dried Mango Slices", "Moringa Powder", "Hibiscus Flowers"],
    services: ["Export Trading", "Quality Inspection", "Logistics Support"],
    keywords: ["organic", "cashew", "mango", "export", "africa", "fair trade"],
    rankingScore: 92,
    rankingTier: "Premium",
    views: 3421,
    inquiries: 156,
    verified: true,
    status: "Active",
    seo: {
      metaTitle: "Okafor Agro Exports - Premium African Agricultural Products",
      metaDescription: "Leading exporter of certified organic cashews and dried fruits from West Africa. Serving global markets with quality and reliability.",
      metaKeywords: ["organic cashew nuts", "african dried mango", "fair trade agriculture", "west africa exports"],
    },
    createdAt: "2023-06-15T10:00:00Z",
    updatedAt: "2024-02-15T14:30:00Z",
  },
  {
    id: "idx2",
    userId: "u2",
    companyName: "Adinkra Fashion House",
    slug: "adinkra-fashion-house",
    logo: "https://images.unsplash.com/photo-1558769132-cb1aea41f9a6?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1509319117101-e7e4ce90e99e?w=1200&h=400&fit=crop",
    tagline: "Authentic African Fashion for the Global Stage",
    description: "Premium African textiles, fashion design, and manufacturing. Specializing in authentic Ankara prints, kente cloth, and custom fashion for international brands.",
    sector: "Fashion & Textiles",
    industries: ["Fashion Design", "Textile Manufacturing", "Export Trading"],
    country: "Ghana",
    city: "Accra",
    website: "www.adinkrafashion.com",
    email: "contact@adinkrafashion.com",
    phone: "+233 234 567 8901",
    foundedYear: 2012,
    employeeCount: "100-200",
    annualRevenue: "$5M - $10M",
    exportMarkets: ["United States", "United Kingdom", "Canada", "France", "South Africa"],
    certifications: ["Eco-Tex Standard", "Quality Certified", "Export Excellence Award"],
    products: ["Ankara Wax Prints", "Kente Cloth", "Custom Fashion Designs", "Accessories"],
    services: ["Fashion Design", "Textile Manufacturing", "Custom Branding"],
    keywords: ["african fashion", "ankara", "kente", "textiles", "wax print"],
    rankingScore: 95,
    rankingTier: "Elite",
    views: 5234,
    inquiries: 289,
    verified: true,
    status: "Active",
    seo: {
      metaTitle: "Adinkra Fashion House - Premium African Textiles & Fashion",
      metaDescription: "Leading African fashion brand specializing in authentic Ankara prints and kente cloth for international markets.",
      metaKeywords: ["african fashion", "ankara fabric", "kente cloth", "ghana textiles"],
    },
    createdAt: "2022-03-20T09:00:00Z",
    updatedAt: "2024-02-16T11:00:00Z",
  },
  {
    id: "idx3",
    userId: "u3",
    companyName: "TechBridge Solutions Africa",
    slug: "techbridge-solutions",
    logo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=400&fit=crop",
    tagline: "Innovative Fintech Solutions for African Markets",
    description: "Leading fintech company providing mobile payment solutions, digital banking, and financial inclusion technology across Africa.",
    sector: "Technology & ICT",
    industries: ["Fintech", "Mobile Payments", "Software Development"],
    country: "Kenya",
    city: "Nairobi",
    website: "www.techbridgeafrica.com",
    email: "hello@techbridgeafrica.com",
    phone: "+254 345 678 9012",
    foundedYear: 2018,
    employeeCount: "50-100",
    annualRevenue: "$2M - $5M",
    exportMarkets: ["Kenya", "Tanzania", "Uganda", "Rwanda", "Ethiopia"],
    certifications: ["ISO 27001", "PCI DSS", "SOC 2"],
    products: ["Mobile Payment Gateway", "Digital Wallet", "Banking API", "Merchant Solutions"],
    services: ["Software Development", "API Integration", "Technical Support"],
    keywords: ["fintech", "mobile payments", "digital banking", "africa", "api"],
    rankingScore: 88,
    rankingTier: "Featured",
    views: 2876,
    inquiries: 134,
    verified: true,
    status: "Active",
    seo: {
      metaTitle: "TechBridge Solutions - Fintech Innovation for Africa",
      metaDescription: "Leading fintech provider of mobile payment and digital banking solutions across East Africa.",
      metaKeywords: ["fintech africa", "mobile payments", "digital banking", "payment gateway"],
    },
    createdAt: "2023-01-10T08:00:00Z",
    updatedAt: "2024-02-14T16:00:00Z",
  },
  {
    id: "idx4",
    userId: "u4",
    companyName: "Solar Energy Africa Ltd",
    slug: "solar-energy-africa",
    logo: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=200&h=200&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=1200&h=400&fit=crop",
    tagline: "Powering Africa with Clean Energy Solutions",
    description: "Leading solar energy provider specializing in residential, commercial, and industrial solar installations across Africa.",
    sector: "Energy & Renewables",
    industries: ["Solar Energy", "Renewable Power", "Installation Services"],
    country: "South Africa",
    city: "Johannesburg",
    website: "www.solarenergyafrica.com",
    email: "info@solarenergyafrica.com",
    phone: "+27 456 789 0123",
    foundedYear: 2016,
    employeeCount: "100-200",
    annualRevenue: "$10M - $20M",
    exportMarkets: ["South Africa", "Botswana", "Namibia", "Zimbabwe", "Zambia"],
    certifications: ["ISO 9001", "CE Certified", "RoHS Compliant"],
    products: ["Solar Panels", "Inverters", "Battery Storage", "Solar Street Lights"],
    services: ["System Design", "Installation", "Maintenance", "Consulting"],
    keywords: ["solar energy", "renewable power", "solar panels", "africa", "clean energy"],
    rankingScore: 90,
    rankingTier: "Premium",
    views: 3145,
    inquiries: 178,
    verified: true,
    status: "Active",
    seo: {
      metaTitle: "Solar Energy Africa - Clean Power Solutions",
      metaDescription: "Leading solar energy provider across Southern Africa offering residential and commercial solar installations.",
      metaKeywords: ["solar energy africa", "solar panels", "renewable energy", "solar installation"],
    },
    createdAt: "2023-04-05T10:00:00Z",
    updatedAt: "2024-02-13T12:00:00Z",
  },
];
