import {
  MarketplaceProduct,
  SupplierProfile,
  RFQ,
  MarketplaceOrder,
  Review,
  MarketplaceCategory,
} from "@/types/marketplace";

export const marketplaceCategories: MarketplaceCategory[] = [
  { id: "1", name: "Agriculture & Food", slug: "agriculture-food", icon: "🌾", productCount: 1247 },
  { id: "2", name: "Fashion & Textiles", slug: "fashion-textiles", icon: "👗", productCount: 892 },
  { id: "3", name: "Electronics & Technology", slug: "electronics-tech", icon: "💻", productCount: 634 },
  { id: "4", name: "Manufacturing & Industrial", slug: "manufacturing", icon: "🏭", productCount: 523 },
  { id: "5", name: "Beauty & Personal Care", slug: "beauty-care", icon: "💄", productCount: 456 },
  { id: "6", name: "Home & Furniture", slug: "home-furniture", icon: "🛋️", productCount: 378 },
  { id: "7", name: "Packaging & Printing", slug: "packaging", icon: "📦", productCount: 289 },
  { id: "8", name: "Construction Materials", slug: "construction", icon: "🏗️", productCount: 412 },
];

export const mockMarketplaceProducts: MarketplaceProduct[] = [
  {
    id: "mp1",
    supplierId: "s1",
    name: "Premium Organic Shea Butter - Raw Unrefined",
    description: "100% pure, organic, unrefined shea butter sourced from women cooperatives in Ghana. Rich in vitamins A and E, perfect for cosmetics and skincare manufacturing. Available in bulk quantities with competitive pricing for distributors.",
    category: "Beauty & Personal Care",
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&h=600&fit=crop",
    ],
    minOrderQuantity: 100,
    pricePerUnit: 12.50,
    currency: "USD",
    pricingTiers: [
      { minQuantity: 100, maxQuantity: 499, pricePerUnit: 12.50 },
      { minQuantity: 500, maxQuantity: 999, pricePerUnit: 11.00 },
      { minQuantity: 1000, pricePerUnit: 9.50 },
    ],
    certifications: ["Organic", "Fair Trade", "HACCP"],
    leadTime: "7-14 days",
    availability: "In Stock",
    views: 1247,
    inquiries: 89,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "mp2",
    supplierId: "s2",
    name: "Premium African Print Fabric - Ankara Wax",
    description: "Authentic African wax print fabrics in vibrant designs. 100% cotton, colorfast, 46 inches wide. Perfect for fashion designers, retailers, and manufacturers. Multiple designs available with minimum order of 50 yards per design.",
    category: "Fashion & Textiles",
    images: [
      "https://images.unsplash.com/photo-1509319117101-e7e4ce90e99e?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1558769132-cb1aea41f9a6?w=600&h=600&fit=crop",
    ],
    minOrderQuantity: 50,
    pricePerUnit: 8.00,
    currency: "USD",
    pricingTiers: [
      { minQuantity: 50, maxQuantity: 199, pricePerUnit: 8.00 },
      { minQuantity: 200, maxQuantity: 499, pricePerUnit: 7.20 },
      { minQuantity: 500, pricePerUnit: 6.50 },
    ],
    certifications: ["Eco-Tex", "Quality Certified"],
    leadTime: "10-20 days",
    availability: "In Stock",
    views: 2134,
    inquiries: 156,
    createdAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "mp3",
    supplierId: "s3",
    name: "Grade A Arabica Coffee Beans - Ethiopian Origin",
    description: "Premium single-origin Arabica coffee beans from Ethiopian highlands. Naturally processed, hand-picked, sorted and graded. Ideal for roasters and distributors. SCA score 85+. Available in 60kg jute bags.",
    category: "Agriculture & Food",
    images: [
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=600&fit=crop",
    ],
    minOrderQuantity: 500,
    pricePerUnit: 6.50,
    currency: "USD",
    pricingTiers: [
      { minQuantity: 500, maxQuantity: 2999, pricePerUnit: 6.50 },
      { minQuantity: 3000, maxQuantity: 9999, pricePerUnit: 6.00 },
      { minQuantity: 10000, pricePerUnit: 5.50 },
    ],
    certifications: ["Organic", "Fair Trade", "Rainforest Alliance"],
    leadTime: "14-21 days",
    availability: "In Stock",
    views: 3421,
    inquiries: 234,
    createdAt: "2024-01-10T08:00:00Z",
  },
  {
    id: "mp4",
    supplierId: "s4",
    name: "Solar LED Street Light - 60W All-in-One",
    description: "High-efficiency solar LED street lights with integrated lithium battery and motion sensor. IP65 waterproof, 5-year warranty. Perfect for municipalities, rural electrification, and commercial projects. Installation support available.",
    category: "Electronics & Technology",
    images: [
      "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=600&fit=crop",
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&h=600&fit=crop",
    ],
    minOrderQuantity: 20,
    pricePerUnit: 285.00,
    currency: "USD",
    pricingTiers: [
      { minQuantity: 20, maxQuantity: 49, pricePerUnit: 285.00 },
      { minQuantity: 50, maxQuantity: 99, pricePerUnit: 265.00 },
      { minQuantity: 100, pricePerUnit: 245.00 },
    ],
    certifications: ["CE", "RoHS", "ISO 9001"],
    leadTime: "20-30 days",
    availability: "In Stock",
    views: 892,
    inquiries: 67,
    createdAt: "2024-02-01T11:00:00Z",
  },
];

export const mockSupplierProfiles: SupplierProfile[] = [
  {
    id: "s1",
    userId: "u1",
    companyName: "West Africa Natural Products Ltd",
    tier: "Gold",
    description: "Leading supplier of organic shea butter and natural ingredients to cosmetics manufacturers worldwide. Working directly with women cooperatives across Ghana and Burkina Faso.",
    logo: "https://images.unsplash.com/photo-1599909533879-6bc6d6ce4932?w=150&h=150&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=1200&h=400&fit=crop",
    country: "Ghana",
    yearsInBusiness: 8,
    responseRate: 98,
    responseTime: "< 2 hours",
    totalProducts: 24,
    totalOrders: 342,
    rating: 4.8,
    reviews: 89,
    verificationBadges: ["Verified Supplier", "Trade Assurance", "On-site Checked"],
    mainCategories: ["Beauty & Personal Care", "Agriculture & Food"],
    certifications: ["Organic", "Fair Trade", "HACCP", "ISO 9001"],
  },
  {
    id: "s2",
    userId: "u2",
    companyName: "Adinkra Fashion Exports",
    tier: "Premium",
    description: "Premium African textiles and fashion exports. Specializing in authentic Ankara wax prints, kente cloth, and custom designs for international fashion brands.",
    logo: "https://images.unsplash.com/photo-1558769132-cb1aea41f9a6?w=150&h=150&fit=crop",
    coverImage: "https://images.unsplash.com/photo-1509319117101-e7e4ce90e99e?w=1200&h=400&fit=crop",
    country: "Nigeria",
    yearsInBusiness: 12,
    responseRate: 99,
    responseTime: "< 1 hour",
    totalProducts: 156,
    totalOrders: 1247,
    rating: 4.9,
    reviews: 234,
    verificationBadges: ["Verified Supplier", "Trade Assurance", "Premium Seller"],
    mainCategories: ["Fashion & Textiles"],
    certifications: ["Eco-Tex", "Quality Certified", "Export Excellence"],
  },
];

export const mockRFQs: RFQ[] = [
  {
    id: "rfq1",
    buyerId: "b1",
    title: "Seeking Organic Cocoa Beans - 50 Tons Monthly",
    description: "European chocolate manufacturer seeking reliable supplier of organic certified cocoa beans. Require consistent quality and monthly shipments. Long-term partnership opportunity.",
    category: "Agriculture & Food",
    targetQuantity: 50000,
    targetPrice: 3500,
    deliveryLocation: "Rotterdam, Netherlands",
    deadline: "2024-03-15",
    responses: 12,
    status: "Open",
    createdAt: "2024-02-10T09:00:00Z",
  },
  {
    id: "rfq2",
    buyerId: "b2",
    title: "Solar Panels for Rural Electrification Project",
    description: "Government tender for 5000 solar panels for rural electrification. Must meet international standards. Installation support required.",
    category: "Electronics & Technology",
    targetQuantity: 5000,
    deliveryLocation: "Nairobi, Kenya",
    deadline: "2024-03-30",
    responses: 8,
    status: "Open",
    createdAt: "2024-02-12T14:00:00Z",
  },
];

export const mockMarketplaceOrders: MarketplaceOrder[] = [
  {
    id: "mo1",
    orderId: "AGBC-2024-001234",
    buyerId: "b1",
    supplierId: "s1",
    items: [
      {
        productId: "mp1",
        productName: "Premium Organic Shea Butter",
        quantity: 500,
        pricePerUnit: 11.00,
        totalPrice: 5500,
      },
    ],
    subtotal: 5500,
    shippingCost: 450,
    totalAmount: 5950,
    currency: "USD",
    status: "Shipped",
    paymentMethod: "Escrow",
    escrowId: "esc_001",
    shippingAddress: {
      fullName: "John Cosmetics Ltd",
      company: "John Cosmetics Manufacturing",
      addressLine1: "123 Industrial Avenue",
      city: "Lagos",
      state: "Lagos State",
      country: "Nigeria",
      postalCode: "100001",
      phone: "+234 123 456 7890",
    },
    trackingNumber: "TRK123456789",
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-10T15:30:00Z",
  },
];

export const mockReviews: Review[] = [
  {
    id: "r1",
    productId: "mp1",
    supplierId: "s1",
    buyerId: "b1",
    rating: 5,
    title: "Excellent quality and service",
    content: "Outstanding quality shea butter. Communication was excellent, shipping was fast, and product exceeded expectations. Will definitely order again.",
    verified: true,
    helpful: 12,
    createdAt: "2024-02-15T11:00:00Z",
  },
  {
    id: "r2",
    productId: "mp2",
    supplierId: "s2",
    buyerId: "b2",
    rating: 4,
    title: "Good quality fabrics",
    content: "Quality is good, colors are vibrant. Shipping took slightly longer than expected but supplier kept me updated. Happy with the purchase overall.",
    verified: true,
    helpful: 8,
    createdAt: "2024-02-12T16:00:00Z",
  },
];
