# Generated by Django 5.0.4 on 2026-03-21 09:16

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("company_description", models.TextField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True, null=True)),
                ("year_established", models.IntegerField(blank=True, null=True)),
                (
                    "employee_count",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "annual_revenue",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "primary_sector",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("additional_sectors", models.JSONField(blank=True, default=list)),
                (
                    "membership_tier",
                    models.CharField(
                        choices=[
                            ("free", "Free Tier"),
                            ("pro", "Professional"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                ("onboarding_skipped", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "dp",
                    models.ImageField(blank=True, null=True, upload_to="business/dps/"),
                ),
                (
                    "cover_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="business/covers/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
